volumes:
  db:

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - 'db:/var/lib/postgresql/data/'
    env_file:
      - .env
    ports:
      - '5433:5432'
    restart: always

  cargo_api:
    ports:
      - "8080:8000"
    build: ..
    restart: always
    depends_on:
      - db
    env_file:
      - .env
