version: '3.9'

volumes:
  database:

services:
  database:
    image: postgres:13.0-alpine
    volumes:
      - database:/var/lib/postgresql/data/
    env_file:
      - .env
    restart: always

  cargo_api:
    ports:
      - "8080:8000"
    build:
      context: ..
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - database
    env_file:
      - .env
